## Pandas

Pandas is a fast, powerful, flexible and easy to use open source data analysis and manipulation tool, built on top of the Python programming language.

### Pandas Series

A Pandas Series is like a column in a table. It is a 1-D array holding data of any type.

Importing pandas

In [22]:
import pandas as pd
import numpy as np

### Series from lists

In [23]:
#string
country = ['usa', 'canada', 'mexico','india']
pd.Series(country)

0       usa
1    canada
2    mexico
3     india
dtype: object

In [24]:
#integer
ages = [25, 30, 35, 40]
pd.Series(ages)

0    25
1    30
2    35
3    40
dtype: int64

In [25]:
#custom index
runs= [11,16,6,149,97,45]
cricketers = ['dhoni','kohli','sachin','raina','rohit','yuvi']
run_scored=pd.Series(runs, index=cricketers)
run_scored

dhoni      11
kohli      16
sachin      6
raina     149
rohit      97
yuvi       45
dtype: int64

In [26]:
pd.Series(runs, index=cricketers, name='Runs Scored')

dhoni      11
kohli      16
sachin      6
raina     149
rohit      97
yuvi       45
Name: Runs Scored, dtype: int64

### Series from Dictionaries

In [27]:
marks ={
    'english': 90,
    'maths': 95,
    'hindi': 85,
    'science': 99,
}
marks_scored = pd.Series(marks,name='Marks Scored')
marks_scored

english    90
maths      95
hindi      85
science    99
Name: Marks Scored, dtype: int64

#### Series Attributes

In [28]:
#size
marks_scored.size

4

In [29]:
#dtype
marks_scored.dtype

dtype('int64')

In [30]:
#name
marks_scored.name

'Marks Scored'

In [31]:
#unique
marks_scored.unique()

array([90, 95, 85, 99], dtype=int64)

In [32]:
#index
marks_scored.index

Index(['english', 'maths', 'hindi', 'science'], dtype='object')

In [33]:
run_scored.index

Index(['dhoni', 'kohli', 'sachin', 'raina', 'rohit', 'yuvi'], dtype='object')

In [34]:
#values
run_scored.values

array([ 11,  16,   6, 149,  97,  45], dtype=int64)

In [35]:
bollywood_data=pd.read_csv('bollywood.csv', index_col='movie')

In [36]:
bollywood_data

                                                  lead
movie
Uri: The Surgical Strike                 Vicky Kaushal
Battalion 609                              Vicky Ahuja
The Accidental Prime Minister (film)       Anupam Kher
Why Cheat India                          Emraan Hashmi
Evening Shadows                       Mona Ambegaonkar
...                                                ...
Hum Tumhare Hain Sanam                  Shah Rukh Khan
Aankhen (2002 film)                   Amitabh Bachchan
Saathiya (film)                           Vivek Oberoi
Company (film)                              Ajay Devgn
Awara Paagal Deewana                      Akshay Kumar

[1500 rows x 1 columns]

In [37]:
bollywood_data.head(10)

                                                      lead
movie
Uri: The Surgical Strike                     Vicky Kaushal
Battalion 609                                  Vicky Ahuja
The Accidental Prime Minister (film)           Anupam Kher
Why Cheat India                              Emraan Hashmi
Evening Shadows                           Mona Ambegaonkar
Soni (film)                           Geetika Vidya Ohlyan
Fraud Saiyaan                                 Arshad Warsi
Bombairiya                                    Radhika Apte
Manikarnika: The Queen of Jhansi            Kangana Ranaut
Thackeray (film)                       Nawazuddin Siddiqui

In [38]:
bollywood_data.tail(5)

                                    lead
movie
Hum Tumhare Hain Sanam    Shah Rukh Khan
Aankhen (2002 film)     Amitabh Bachchan
Saathiya (film)             Vivek Oberoi
Company (film)                Ajay Devgn
Awara Paagal Deewana        Akshay Kumar

In [39]:
type(bollywood_data)

pandas.core.frame.DataFrame

In [40]:
bollywood_data.describe()

                lead
count           1500
unique           566
top     Akshay Kumar
freq              48

In [42]:
bollywood_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1500 entries, Uri: The Surgical Strike to Awara Paagal Deewana
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   lead    1500 non-null   object
dtypes: object(1)
memory usage: 23.4+ KB