#### There are several techniques to gather data to do operations in machine learning. Some of the most common methods include:

Working with csv

1. Importing pandas

In [1]:
import pandas as pd

2. Opening a local csv file

In [2]:

bollywood_data = pd.read_csv(r'C:\Users\RADHE\machine-learning\Rehan\DATASET\bollywood.csv', index_col='movie')

In [3]:
bollywood_data.head()

                                                  lead
movie
Uri: The Surgical Strike                 Vicky Kaushal
Battalion 609                              Vicky Ahuja
The Accidental Prime Minister (film)       Anupam Kher
Why Cheat India                          Emraan Hashmi
Evening Shadows                       Mona Ambegaonkar

3. Opening a csv file from a URL

In [4]:
import requests 
from io import StringIO
url = 'https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv'
headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3'}
response = requests.get(url, headers=headers)
chipotle_data = pd.read_csv(StringIO(response.text), sep='\t')
chipotle_data.head()

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98

4. Sep parameter

In [5]:
pd.read_csv(r'C:\Users\RADHE\machine-learning\Rehan\DATASET\bollywood.csv', index_col='movie', sep=',')

                                                  lead
movie
Uri: The Surgical Strike                 Vicky Kaushal
Battalion 609                              Vicky Ahuja
The Accidental Prime Minister (film)       Anupam Kher
Why Cheat India                          Emraan Hashmi
Evening Shadows                       Mona Ambegaonkar
...                                                ...
Hum Tumhare Hain Sanam                  Shah Rukh Khan
Aankhen (2002 film)                   Amitabh Bachchan
Saathiya (film)                           Vivek Oberoi
Company (film)                              Ajay Devgn
Awara Paagal Deewana                      Akshay Kumar

[1500 rows x 1 columns]

sep = '\t' for tab-separated values,    
sep = ',' for comma-separated values,   
sep = ';' for semicolon-separated values, etc.

5. Names parameter

 While importing data using pandas, there is an attribute called names using which we can specify the column names of the data. If the data has no header, we can use this attribute to specify the column names.

6. Index_col parameter

 The index_col parameter is used to specify the column that should be used as the index of the DataFrame. By default, pandas will create a new integer index for the DataFrame, but you can use the index_col parameter to specify a column to use as the index instead.

7. Header parameter

 The header parameter is used to specify the row that should be used as the header of the DataFrame. By default, pandas will use the first row of the data as the header, but you can use the header parameter to specify a different row to use as the header instead.

8. use_cols parameter

 The usecols parameter is used to specify a subset of columns to read from the data. By default, pandas will read all columns from the data, but you can use the usecols parameter to specify a list of column names or indices to read instead.

9. Squeeze parameter

 The squeeze parameter is used to convert a DataFrame with a single column into a Series. By default, pandas will return a DataFrame even if it has only one column, but you can use the squeeze parameter to return a Series instead.

10. Skiprows parameter

 The skiprows parameter is used to skip a specified number of rows from the beginning of the data. By default, pandas will read all rows from the data, but you can use the skiprows parameter to skip a specified number of rows instead.

11. nrows parameter

 The nrows parameter is used to specify the number of rows to read from the data. By default, pandas will read all rows from the data, but you can use the nrows parameter to read a specified number of rows instead.

In [6]:
pd.read_csv(r'C:\Users\RADHE\machine-learning\Rehan\DATASET\bollywood.csv', nrows=100, sep=',')

                                   movie              lead
0               Uri: The Surgical Strike     Vicky Kaushal
1                          Battalion 609       Vicky Ahuja
2   The Accidental Prime Minister (film)       Anupam Kher
3                        Why Cheat India     Emraan Hashmi
4                        Evening Shadows  Mona Ambegaonkar
..                                   ...               ...
95                             3 Storeys       Aisha Ahmed
96                      Raid (2018 film)        Ajay Devgn
97                                Hichki      Rani Mukerji
98                   Missing (2018 film)    Manoj Bajpayee
99                              Baaghi 2      Tiger Shroff

[100 rows x 2 columns]

12. Encoding parameter

 The encoding parameter is used to specify the encoding of the data. By default, pandas will use the system's default encoding, but you can use the encoding parameter to specify a different encoding if needed.

In [7]:
pd.read_csv(r'C:\Users\RADHE\machine-learning\Rehan\DATASET\bollywood.csv', encoding='latin-1')

                                     movie              lead
0                 Uri: The Surgical Strike     Vicky Kaushal
1                            Battalion 609       Vicky Ahuja
2     The Accidental Prime Minister (film)       Anupam Kher
3                          Why Cheat India     Emraan Hashmi
4                          Evening Shadows  Mona Ambegaonkar
...                                    ...               ...
1495                Hum Tumhare Hain Sanam    Shah Rukh Khan
1496                   Aankhen (2002 film)  Amitabh Bachchan
1497                       Saathiya (film)      Vivek Oberoi
1498                        Company (film)        Ajay Devgn
1499                  Awara Paagal Deewana      Akshay Kumar

[1500 rows x 2 columns]

13. Skip bad lines parameter

 The skip_bad_lines parameter is used to skip lines that are malformed or contain errors. By default, pandas will raise an error if it encounters a bad line, but you can use the skip_bad_lines parameter to skip those lines instead.

 Example: pd.read_csv('data.csv', skip_bad_lines=True)

 Suppose you have 8 columns in all of the rows, but in some rows, there are only 7 columns. In that case, pandas will raise an error while reading the data. To avoid this error, you can use the skip_bad_lines parameter to skip those rows with missing columns.

14. dtypes parameter

 The dtypes parameter is used to specify the data types of the columns in the DataFrame. By default, pandas will infer the data types of the columns based on the data, but you can use the dtypes parameter to specify the data types explicitly.

 Example: pd.read_csv('data.csv', dtype={'column1': 'int64', 'column2': 'float64'})

In [8]:
ipl_data = pd.read_csv(r'C:\Users\RADHE\machine-learning\Rehan\DATASET\IPL.csv')
ipl_data.describe()

C:\Users\RADHE\AppData\Local\Temp\ipykernel_11740\2752634765.py:1: DtypeWarning: Columns (27,28,29,30,42,45,46,47,50) have mixed types. Specify dtype option on import or set low_memory=False.
  ipl_data = pd.read_csv(r'C:\Users\RADHE\machine-learning\Rehan\DATASET\IPL.csv')

,match_id,innings,over,ball,ball_no,bat_pos,runs_batter,balls_faced,valid_ball,runs_extras,...,balls_per_over,overs,team_runs,team_balls,team_wicket,power_surge_start,batter_runs,batter_balls,bowler_wicket,striker_out
count,2.957320e+05,295732.000000,295732.000000,295732.000000,295732.000000,295732.000000,295732.000000,295732.000000,295732.000000,295732.000000,...,295732.0,295732.0,295732.000000,295732.000000,295732.000000,0.0,295732.000000,295732.000000,295732.000000,295732.000000
mean,9.770551e+05,1.482728,9.190331,3.488807,9.539212,3.621847,1.290117,0.966605,0.962459,0.068336,...,6.0,20.0,78.146291,58.592844,2.466067,NaN,18.514882,13.982883,0.045609,0.047793
std,3.953255e+05,0.502436,5.679690,1.708185,5.681079,2.173463,1.664418,0.179666,0.190083,0.342939,...,0.0,0.0,50.698248,34.106127,2.105231,NaN,18.767165,11.811388,0.208636,0.213329
min,3.359820e+05,1.000000,0.000000,1.000000,0.100000,1.000000,0.000000,0.000000,0.000000,0.000000,...,6.0,20.0,0.000000,0.000000,0.000000,NaN,0.000000,0.000000,0.000000,0.000000
25%,5.483720e+05,1.000000,4.000000,2.000000,4.500000,2.000000,0.000000,1.000000,1.000000,0.000000,...,6.0,20.0,36.000000,29.000000,1.000000,NaN,4.000000,5.000000,0.000000,0.000000
50%,1.082639e+06,1.000000,9.000000,3.000000,9.400000,3.000000,1.000000,1.000000,1.000000,0.000000,...,6.0,20.0,74.000000,58.000000,2.000000,NaN,13.000000,11.000000,0.000000,0.000000
75%,1.304103e+06,2.000000,14.000000,5.000000,14.400000,5.000000,1.000000,1.000000,1.000000,0.000000,...,6.0,20.0,115.000000,88.000000,4.000000,NaN,27.000000,20.000000,0.000000,0.000000
max,1.535465e+06,6.000000,19.000000,7.000000,19.600000,11.000000,6.000000,1.000000,1.000000,7.000000,...,6.0,20.0,287.000000,121.000000,10.000000,NaN,175.000000,73.000000,1.000000,1.000000

In [9]:
ipl_data.shape

(295732, 64)

In [10]:
ipl_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 295732 entries, 0 to 295731
Data columns (total 64 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   match_id           295732 non-null  int64
 1   date               295732 non-null  object
 2   match_type         295732 non-null  object
 3   event_name         295732 non-null  object
 4   innings            295732 non-null  int64
 5   batting_team       295732 non-null  object
 6   bowling_team       295732 non-null  object
 7   over               295732 non-null  int64
 8   ball               295732 non-null  int64
 9   ball_no            295732 non-null  float64
 10  batter             295732 non-null  object
 11  bat_pos            295732 non-null  int64
 12  runs_batter        295732 non-null  int64
 13  balls_faced        295732 non-null  int64
 14  bowler             295732 non-null  object
 15  valid_ball         295732 non-null  int64
 16  runs_extras        295732 non-null  int64
 17  runs_total         295732 non-null  int64
 18  runs_bowler        295732 non-null  int64
 19  runs_not_boundary  295732 non-null  bool
 20  extra_type         16227 non-null   object
 21  non_striker        295732 non-null  object
 22  non_striker_pos    295732 non-null  int64
 23  wicket_kind        14705 non-null   object
 24  player_out         14705 non-null   object
 25  fielders           10721 non-null   object
 26  runs_target        142303 non-null  float64
 27  review_batter      990 non-null     object
 28  team_reviewed      990 non-null     object
 29  review_decision    990 non-null     object
 30  umpire             990 non-null     object
 31  umpires_call       295732 non-null  bool
 32  player_of_match    295732 non-null  object
 33  match_won_by       295732 non-null  object
 34  win_outcome        290752 non-null  object
 35  toss_winner        295732 non-null  object
 36  toss_decision      295732 non-null  object
 37  venue              295732 non-null  object
 38  city               295732 non-null  object
 39  day                295732 non-null  int64
 40  month              295732 non-null  int64
 41  year               295732 non-null  int64
 42  season             295732 non-null  object
 43  gender             295732 non-null  object
 44  team_type          295732 non-null  object
 45  superover_winner   4152 non-null    object
 46  result_type        4980 non-null    object
 47  method             4131 non-null    object
 48  balls_per_over     295732 non-null  int64
 49  overs              295732 non-null  int64
 50  event_match_no     295732 non-null  object
 51  stage              295732 non-null  object
 52  match_number       295732 non-null  object
 53  team_runs          295732 non-null  int64
 54  team_balls         295732 non-null  int64
 55  team_wicket        295732 non-null  int64
 56  new_batter         14163 non-null   object
 57  power_surge_start  0 non-null       float64
 58  batter_runs        295732 non-null  int64
 59  batter_balls       295732 non-null  int64
 60  bowler_wicket      295732 non-null  int64
 61  batting_partners   295732 non-null  object
 62  striker_out        295732 non-null  int64
 63  next_batter        14163 non-null   object
dtypes: bool(2), float64(3), int64(24), object(35)
memory usage: 140.5+ MB

In [11]:
ipl_data.isnull().sum().head(27)

match_id                  0
date                      0
match_type                0
event_name                0
innings                   0
batting_team              0
bowling_team              0
over                      0
ball                      0
ball_no                   0
batter                    0
bat_pos                   0
runs_batter               0
balls_faced               0
bowler                    0
valid_ball                0
runs_extras               0
runs_total                0
runs_bowler               0
runs_not_boundary         0
extra_type           279505
non_striker               0
non_striker_pos           0
wicket_kind          281027
player_out           281027
fielders             285011
runs_target          153429
dtype: int64

In [12]:
if ipl_data is None:
    ipl_data = pd.read_csv(r'C:\Users\RADHE\machine-learning\Rehan\DATASET\IPL.csv')

ipl_data = ipl_data.drop(
    columns=["extra_type","umpire","superover_winner","result_type","method","new_batter","power_surge_start", "next_batter","review_batter","team_reviewed","review_decision", "runs_target", "wicket_kind", "player_out", "fielders"],
    errors="ignore"
)
ipl_data.shape

(295732, 49)

In [13]:
ipl_data.isnull().sum().head(25)

match_id             0
date                 0
match_type           0
event_name           0
innings              0
batting_team         0
bowling_team         0
over                 0
ball                 0
ball_no              0
batter               0
bat_pos              0
runs_batter          0
balls_faced          0
bowler               0
valid_ball           0
runs_extras          0
runs_total           0
runs_bowler          0
runs_not_boundary    0
non_striker          0
non_striker_pos      0
umpires_call         0
player_of_match      0
match_won_by         0
dtype: int64

In [14]:
IPL = pd.read_csv(r'C:\Users\RADHE\machine-learning\Rehan\DATASET\IPL.csv', parse_dates=['date']).info()
ipl_data.head()

C:\Users\RADHE\AppData\Local\Temp\ipykernel_11740\214733393.py:1: DtypeWarning: Columns (27,28,29,30,42,45,46,47,50) have mixed types. Specify dtype option on import or set low_memory=False.
  IPL = pd.read_csv(r'C:\Users\RADHE\machine-learning\Rehan\DATASET\IPL.csv', parse_dates=['date']).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 295732 entries, 0 to 295731
Data columns (total 64 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   match_id           295732 non-null  int64
 1   date               295732 non-null  datetime64[ns]
 2   match_type         295732 non-null  object
 3   event_name         295732 non-null  object
 4   innings            295732 non-null  int64
 5   batting_team       295732 non-null  object
 6   bowling_team       295732 non-null  object
 7   over               295732 non-null  int64
 8   ball               295732 non-null  int64
 9   ball_no            295732 non-null  float64
 10  batter             295732 non-null  object
 11  bat_pos            295732 non-null  int64
 12  runs_batter        295732 non-null  int64
 13  balls_faced        295732 non-null  int64
 14  bowler             295732 non-null  object
 15  valid_ball         295732 non-null  int64
 16  runs_extras        295732 non-null  int64
 17  runs_total         295732 non-null  int64
 18  runs_bowler        295732 non-null  int64
 19  runs_not_boundary  295732 non-null  bool
 20  extra_type         16227 non-null   object
 21  non_striker        295732 non-null  object
 22  non_striker_pos    295732 non-null  int64
 23  wicket_kind        14705 non-null   object
 24  player_out         14705 non-null   object
 25  fielders           10721 non-null   object
 26  runs_target        142303 non-null  float64
 27  review_batter      990 non-null     object
 28  team_reviewed      990 non-null     object
 29  review_decision    990 non-null     object
 30  umpire             990 non-null     object
 31  umpires_call       295732 non-null  bool
 32  player_of_match    295732 non-null  object
 33  match_won_by       295732 non-null  object
 34  win_outcome        290752 non-null  object
 35  toss_winner        295732 non-null  object
 36  toss_decision      295732 non-null  object
 37  venue              295732 non-null  object
 38  city               295732 non-null  object
 39  day                295732 non-null  int64
 40  month              295732 non-null  int64
 41  year               295732 non-null  int64
 42  season             295732 non-null  object
 43  gender             295732 non-null  object
 44  team_type          295732 non-null  object
 45  superover_winner   4152 non-null    object
 46  result_type        4980 non-null    object
 47  method             4131 non-null    object
 48  balls_per_over     295732 non-null  int64
 49  overs              295732 non-null  int64
 50  event_match_no     295732 non-null  object
 51  stage              295732 non-null  object
 52  match_number       295732 non-null  object
 53  team_runs          295732 non-null  int64
 54  team_balls         295732 non-null  int64
 55  team_wicket        295732 non-null  int64
 56  new_batter         14163 non-null   object
 57  power_surge_start  0 non-null       float64
 58  batter_runs        295732 non-null  int64
 59  batter_balls       295732 non-null  int64
 60  bowler_wicket      295732 non-null  int64
 61  batting_partners   295732 non-null  object
 62  striker_out        295732 non-null  int64
 63  next_batter        14163 non-null   object
dtypes: bool(2), datetime64[ns](1), float64(3), int64(24), object(34)
memory usage: 140.5+ MB

,match_id,date,match_type,event_name,innings,batting_team,bowling_team,over,ball,ball_no,...,stage,match_number,team_runs,team_balls,team_wicket,batter_runs,batter_balls,bowler_wicket,batting_partners,striker_out
0,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,0.1,...,Unknown,Unknown,1,1,0,0,1,0,BB McCullum|SC Ganguly,0
1,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,0.2,...,Unknown,Unknown,1,2,0,0,1,0,BB McCullum|SC Ganguly,0
2,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,0.3,...,Unknown,Unknown,2,2,0,0,1,0,BB McCullum|SC Ganguly,0
3,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,0.3,...,Unknown,Unknown,2,3,0,0,2,0,BB McCullum|SC Ganguly,0
4,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,0.4,...,Unknown,Unknown,2,4,0,0,3,0,BB McCullum|SC Ganguly,0

15. Converters parameter

 The converters parameter is used to specify a dictionary of functions to apply to the columns of the DataFrame. By default, pandas will not apply any functions to the columns, but you can use the converters parameter to apply custom functions to the columns.

 Example: pd.read_csv('data.csv', converters={'column1': lambda x: x.upper(), 'column2': lambda x: float(x)})

In [15]:
ipl_data

,match_id,date,match_type,event_name,innings,batting_team,bowling_team,over,ball,ball_no,...,stage,match_number,team_runs,team_balls,team_wicket,batter_runs,batter_balls,bowler_wicket,batting_partners,striker_out
0,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,0.1,...,Unknown,Unknown,1,1,0,0,1,0,BB McCullum|SC Ganguly,0
1,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,0.2,...,Unknown,Unknown,1,2,0,0,1,0,BB McCullum|SC Ganguly,0
2,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,0.3,...,Unknown,Unknown,2,2,0,0,1,0,BB McCullum|SC Ganguly,0
3,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,0.3,...,Unknown,Unknown,2,3,0,0,2,0,BB McCullum|SC Ganguly,0
4,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,0.4,...,Unknown,Unknown,2,4,0,0,3,0,BB McCullum|SC Ganguly,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295727,1535465,2026-05-31,T20,Indian Premier League,2,Royal Challengers Bengaluru,Gujarat Titans,17,2,17.2,...,Final,Unknown,150,104,5,65,40,0,JM Sharma|V Kohli,0
295728,1535465,2026-05-31,T20,Indian Premier League,2,Royal Challengers Bengaluru,Gujarat Titans,17,3,17.3,...,Final,Unknown,150,105,5,10,13,0,JM Sharma|V Kohli,0
295729,1535465,2026-05-31,T20,Indian Premier League,2,Royal Challengers Bengaluru,Gujarat Titans,17,4,17.4,...,Final,Unknown,151,106,5,11,14,0,JM Sharma|V Kohli,0
295730,1535465,2026-05-31,T20,Indian Premier League,2,Royal Challengers Bengaluru,Gujarat Titans,17,5,17.5,...,Final,Unknown,155,107,5,69,41,0,JM Sharma|V Kohli,0
295731,1535465,2026-05-31,T20,Indian Premier League,2,Royal Challengers Bengaluru,Gujarat Titans,17,6,17.6,...,Final,Unknown,161,108,5,75,42,0,JM Sharma|V Kohli,0

In [16]:
def rename(name):
    name = name.strip()

    if name == "Royal Challengers Bengaluru":
        return "RCB"

    return name

IPL = pd.read_csv(
    r'C:\Users\RADHE\machine-learning\Rehan\DATASET\IPL.csv',
    converters={'batting_team': rename}
)
IPL.tail(100)

C:\Users\RADHE\AppData\Local\Temp\ipykernel_11740\1932824087.py:9: DtypeWarning: Columns (27,28,29,30,42,45,46,47,50) have mixed types. Specify dtype option on import or set low_memory=False.
  IPL = pd.read_csv(

,match_id,date,match_type,event_name,innings,batting_team,bowling_team,over,ball,ball_no,...,team_balls,team_wicket,new_batter,power_surge_start,batter_runs,batter_balls,bowler_wicket,batting_partners,striker_out,next_batter
295632,1535465,2026-05-31,T20,Indian Premier League,2,RCB,Gujarat Titans,1,4,1.4,...,10,0,NaN,NaN,18,9,0,V Kohli|VR Iyer,0,NaN
295633,1535465,2026-05-31,T20,Indian Premier League,2,RCB,Gujarat Titans,1,5,1.5,...,11,0,NaN,NaN,18,10,0,V Kohli|VR Iyer,0,NaN
295634,1535465,2026-05-31,T20,Indian Premier League,2,RCB,Gujarat Titans,1,6,1.6,...,12,0,NaN,NaN,22,11,0,V Kohli|VR Iyer,0,NaN
295635,1535465,2026-05-31,T20,Indian Premier League,2,RCB,Gujarat Titans,2,1,2.1,...,13,0,NaN,NaN,4,2,0,V Kohli|VR Iyer,0,NaN
295636,1535465,2026-05-31,T20,Indian Premier League,2,RCB,Gujarat Titans,2,2,2.2,...,14,0,NaN,NaN,4,3,0,V Kohli|VR Iyer,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295727,1535465,2026-05-31,T20,Indian Premier League,2,RCB,Gujarat Titans,17,2,17.2,...,104,5,NaN,NaN,65,40,0,JM Sharma|V Kohli,0,NaN
295728,1535465,2026-05-31,T20,Indian Premier League,2,RCB,Gujarat Titans,17,3,17.3,...,105,5,NaN,NaN,10,13,0,JM Sharma|V Kohli,0,NaN
295729,1535465,2026-05-31,T20,Indian Premier League,2,RCB,Gujarat Titans,17,4,17.4,...,106,5,NaN,NaN,11,14,0,JM Sharma|V Kohli,0,NaN
295730,1535465,2026-05-31,T20,Indian Premier League,2,RCB,Gujarat Titans,17,5,17.5,...,107,5,NaN,NaN,69,41,0,JM Sharma|V Kohli,0,NaN
295731,1535465,2026-05-31,T20,Indian Premier League,2,RCB,Gujarat Titans,17,6,17.6,...,108,5,NaN,NaN,75,42,0,JM Sharma|V Kohli,0,NaN

16. na_values parameter

 The na_values parameter is used to specify a list of values that should be treated as missing or NaN in the DataFrame. By default, pandas will treat certain values (such as 'NaN', 'null', etc.) as missing, but you can use the na_values parameter to specify additional values to treat as missing.

 Example: pd.read_csv('data.csv', na_values=['NA', 'missing', 'n/a'])

17. low memory parameter

 The low_memory parameter is used to optimize memory usage when reading large datasets. By default, pandas will read the entire dataset into memory, which can be inefficient for large datasets. Setting low_memory=True allows pandas to read the data in smaller chunks, which can help reduce memory usage.

 Example: pd.read_csv('data.csv', low_memory=True)

18. Loading a huge dataset in chunks

 When working with large datasets, it's often necessary to load the data in smaller chunks rather than all at once. This can help manage memory usage and improve performance. The `chunksize` parameter in `pd.read_csv()` allows you to specify the number of rows to read at a time.

 Example: pd.read_csv('data.csv', chunksize=1000)

In [ ]:
ipl_data.shape

(295732, 49)

In [18]:
dfs = pd.read_csv(r'C:\Users\RADHE\machine-learning\Rehan\DATASET\IPL.csv', chunksize=20000, low_memory=False)

In [19]:
for chunk in dfs:
    print(chunk.shape)

(20000, 64)
(20000, 64)
(20000, 64)
(20000, 64)
(20000, 64)
(20000, 64)
(20000, 64)
(20000, 64)
(20000, 64)
(20000, 64)
(20000, 64)
(20000, 64)
(20000, 64)
(20000, 64)
(15732, 64)